### ISSUE TITLE
Remove Archive and Jobs tabs and pages

### ISSUE THREAD

**Issue by cb0806151** [sgfdevs/sgf.dev#30]
These two features were never developed or are not being used. Can they be removed?

**Comment by glitchedmob** [comment]
I think they can be for now. But I think we should make plans to eventually bring them back.

- Jobs: Because it could be a benefit for our sponsors, letting us raise the price on our plans and/or just add more sponsors
- Archive: The concept here was to have a page for every event we've ever hosted and embed the recording if we have it. Having a lot of content like this out there could be a big boost to our SEO

**Comment by Ryan-DL** [comment]
Going to clsoe this for now, we've addressed as such in https://github.com/sgfdevs/sgf.dev/pull/32.

Thanks!
